name: ASL Build Pipeline

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: install cppunit
          uses: actions/checkout@v2
        - name: CMake Configuration
          run: cmake .
        - name: Build from source
          run: cmake --build .
