name: ASL Build Pipeline

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
      run: cmake .
      - name: CMake Configuration
      run: cmake --build .
      - name: Build from source
