name: ASL build and test pipeline

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build_all:
      runs-on: ubuntu-latest
      steps:
        - name: install cppunit
          uses: actions/checkout@v2
        - name: CMake Configuration
          run: cmake .
        - name: Build from source
          run: cmake --build .
  cpplint:
      runs-on: ubuntu-latest
      steps:
        - name: install cppunit
          uses: actions/checkout@v2
        - name: Install cpplint
          run: pip install cpplint
        - name: Run cpplint
          run: cpplint `find ./src -name \*.h -or -name \*.cpp`
  test:
      runs-on: ubuntu-latest
      steps:
        - name: install cppunit
          uses: actions/checkout@v2
        - name: CMake Configuration
          run: cmake .
        - name: Build from source
          run: cmake --build .
        - name: Run test cases
          run: ctest --output-on-failure
